ws_uri = "ws://localhost:7125/websocket"
output_dir = "/home/pi/image-data"
fps = 0.05 # 20 sec between each image

[[cam]]
type = "rpi"
device = "/base/axi/pcie@1000120000/rp1/i2c@88000/imx296@1a"

[[cam]]
type = "usb"
device = "/base/axi/pcie@1000120000/rp1/usb@300000-1:1.0-0bda:0561"

[[cam]]
type = "usb"
device = "/base/axi/pcie@1000120000/rp1/usb@300000-2:1.0-1bcf:28c5"
