ws_uri = "ws://localhost:7125/websocket"
output_dir = "/home/pi/image-data"
fps = 0.05 # 20 sec between each image

[[cam]]
name = "nozzle"
uri = "http://127.0.0.1:8001/snapshot"

[[cam]]
name = "name"
uri = "http://127.0.0.1:8002/snapshot"
