#!/usr/bin/env bash
#### Klipper auto image
#### https://github.com/trymauren/klipper-auto-image

set -Eeou pipefail # Error handling

# KAI = klipper-auto-image
BASE_KAI_PATH="$(dirname "$(dirname "$(readlink -fm "$0")")")"
PY_BIN="${HOME}/.local/bin/uv"
KAI_CFG="${HOME}/printer_data/config/klipper-auto-image.conf"

debug_msg() {
    printf "DEBUG: %s\n" "${1}"
}

help_msg() {
    echo -e "Klipper auto image\nUsage:"
    echo -e "\t klipper-auto-image [Options]"
    echo -e "\n\t\t-h Prints this help."
    echo -e "\n\t\t-c </path/to/configfile>\n\t\t\tPath to your klipper-auto-image.conf"
}

wrong_args_msg() {
    echo -e "klipper-auto-image: Wrong Arguments!"
    echo -e "\n\tTry: klipper-auto-image -h\n"
}

"${PY_BIN}" run "${BASE_KAI_PATH}/run.py" "$@"

### Loop to keep running
while true; do
    sleep 1
done
